version: '2'
services:
  express-api-es6-example:
    build: .
    volumes:
      - .env.docker:/app/.env
    ports:
      - "8848:8848"
    entrypoint: /bin/sh
    command: -c "sleep 5 && npm run migrate && npm run seed && npm run start:dev"
    depends_on:
      - pg
    links:
      - pg
  pg:
    image: postgres:9-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=express
